import type { Player } from "../types/index"

export const players: Player[] = [
	{
		id: 1,
		firstName: "Alice",
		lastName: "Martin",
		jerseyNumber: 12,
		position: undefined,
		isCaptain: false,
		age: 24,
		bats: "right",
		throws: "right",
		photoUrl: "",
	},
	{
		id: 2,
		firstName: "Bob",
		lastName: "Dupont",
		jerseyNumber: 7,
		position: undefined,
		isCaptain: true,
		age: 29,
		bats: "left",
		throws: "right",
		photoUrl: "",
	},
	{
		id: 3,
		firstName: "Charlie",
		lastName: "Lemoine",
		jerseyNumber: 34,
		age: 22,
		bats: "switch",
		throws: "left",
	},
	{
		id: 4,
		firstName: "David",
		lastName: "Moreau",
		jerseyNumber: 5,
		age: 26,
		bats: "right",
		throws: "right",
	},
	{
		id: 5,
		firstName: "Eva",
		lastName: "Girard",
		jerseyNumber: 21,
		age: 23,
		bats: "left",
		throws: "left",
	},
	{
		id: 6,
		firstName: "Frank",
		lastName: "Bernard",
		jerseyNumber: 18,
		age: 30,
		bats: "right",
		throws: "right",
	},
	{
		id: 7,
		firstName: "Grace",
		lastName: "Faure",
		jerseyNumber: 9,
		age: 25,
		bats: "right",
		throws: "left",
	},
	{
		id: 8,
		firstName: "Hugo",
		lastName: "Clément",
		jerseyNumber: 2,
		age: 28,
		bats: "left",
		throws: "right",
	},
	{
		id: 9,
		firstName: "Iris",
		lastName: "Leroy",
		jerseyNumber: 11,
		age: 27,
		bats: "switch",
		throws: "right",
	},
]
